source 'https://rubygems.org'

gem 'authlogic'
gem 'aws-sdk'
gem 'bcrypt'
gem 'bootstrap-sass'
gem 'declarative_authorization'
gem 'haml'
gem 'jquery-rails'
gem 'paperclip'
gem 'pg'
gem 'pry-rails'
gem 'rails', '4.1.1'
gem 'sass-rails', '~> 4.0.3'
gem 'simple_form', '3.1.0.rc1'
gem 'spring', group: :development
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'
